[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://your-api-url-here"
  VITE_API_KEY = "your-api-key-here"
