[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22" # or "20" if you want LTS

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

[functions]
  directory = "netlify/functions"
